### ISSUE TITLE
OrderNumber numeric 15

### ISSUE THREAD

**Issue by machj** [marazt/gpwebpay-net#2]
OrderNumber parameter can have, based on the documentation of the bank, 15 digits. In this library is OrderNumber limited to integer type, max. size 2147483647 (10 digits, plus it must start with 1 or 2 ...). 

Could you please change in the next version the type of the OrderNumber to uint or something like this? I need order numbers with more characters/digits than 10 (we have predefined prefixes for orders...).

Probably  to modify SDK Models: PaymentRequest.cs line 25 and PaymentResponse.cs line 24. 

Thank you.

Honza

**Comment by marazt** [comment]
Hi. Thanks. I've check it and you are right. So set `OrderNumber` to `ulong` and additional validation for maximal `OrderNumber` length by particular bank could be the solution. 
I'll update it.

**Comment by marazt** [comment]
Hi @machj, I have updated OrderNumber (and other int/long where it make sense) types to respective unsigned types. I did not add validation for target bank limits for now. It can be validated by you as library user. But it can be probably added to the lib as well. 
Please, let me know if the fix helped you.
the new version is **v1.4.0**.

Regards,

Marek

**Comment by machj** [comment]
> Please, let me know if the fix helped you.
> the new version is **v1.4.0**.

Hello,
I've changed datatypes in my database and application to ulong (incl. function definitions with int OrderNum, where was at first "arithmetic overflow" error - can be a problem for some users?).

It works perfectly for me with the new version v.1.4.0 .

Thank you!

Honza

**Comment by marazt** [comment]
Ok, I'm closing the issue :).
